CREATE TABLE gestionstagesalternances.utilisateur (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) CHECK (role IN ('ETUDIANT', 'ENTREPRISE', 'ADMIN'))
);

CREATE TABLE gestionstagesalternances.admin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    telephone VARCHAR(50),
    adresse VARCHAR(255),
    user_id INT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES gestionstagesalternances.utilisateur(id)
);

CREATE TABLE gestionstagesalternances.entreprise (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100),
    telephone VARCHAR(50),
    adresse VARCHAR(255),
    site_web VARCHAR(255),
    secteur_activite VARCHAR(100),
    user_id INT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES gestionstagesalternances.utilisateur(id)
);

CREATE TABLE gestionstagesalternances.etudiant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(100),
    prenom VARCHAR(100),
    telephone VARCHAR(50),
    adresse VARCHAR(255),
    niveau_etude VARCHAR(100),
    specialite VARCHAR(100),
    cv VARCHAR(255),
    user_id INT UNIQUE,
    FOREIGN KEY (user_id) REFERENCES gestionstagesalternances.utilisateur(id)
);

CREATE TABLE gestionstagesalternances.stage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titre VARCHAR(100),
    description TEXT,
    lieu VARCHAR(100),
    duree VARCHAR(50),
    date_debut VARCHAR(50),
    date_fin VARCHAR(50),
    etudiant_id INT,
    entreprise_id INT,
    type VARCHAR(20) CHECK (type IN ('STAGE', 'ALTERNANCE')),
    FOREIGN KEY (etudiant_id) REFERENCES gestionstagesalternances.utilisateur(id),
    FOREIGN KEY (entreprise_id) REFERENCES gestionstagesalternances.entreprise(id)
);

CREATE TABLE gestionstagesalternances.candidature (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_candidature DATE,
    message TEXT,
    statut VARCHAR(20) CHECK (statut IN ('EN_ATTENTE', 'ACCEPTEE', 'REFUSEE')),
    etudiant_id INT,
    stage_id INT,
    FOREIGN KEY (etudiant_id) REFERENCES gestionstagesalternances.etudiant(id),
    FOREIGN KEY (stage_id) REFERENCES gestionstagesalternances.stage(id)
);