import { Routes } from '@angular/router';
import { AboutComponent } from './ts/autre/about.component';
import { ContactComponent } from './ts/autre/contact.component';
import { HomeComponent } from './ts/autre/home.component';
import { AdminListComponent } from './ts/list/admin-list.component';
import { AdminFormComponent } from './ts/form/admin-form.component';
import { AdminDetailComponent } from './ts/detail/admin-detail.component';
import { CandidatureListComponent } from './ts/list/candidature-list.component';
import { CandidatureFormComponent } from './ts/form/candidature-form.component';
import { CandidatureDetailComponent } from './ts/detail/candidature-detail.component';
import { EntrepriseListComponent } from './ts/list/entreprise-list.component';
import { EntrepriseFormComponent } from './ts/form/entreprise-form.component';
import { EntrepriseDetailComponent } from './ts/detail/entreprise-detail.component';
import { EtudiantListComponent } from './ts/list/etudiant-list.component';
import { EtudiantFormComponent } from './ts/form/etudiant-form.component';
import { EtudiantDetailComponent } from './ts/detail/etudiant-detail.component';
import { StageListComponent } from './ts/list/stage-list.component';
import { StageFormComponent } from './ts/form/stage-form.component';
import { StageDetailComponent } from './ts/detail/stage-detail.component';
import { UserListComponent } from './ts/list/user-list.component';
import { UserFormComponent } from './ts/form/user-form.component';
import { UserDetailComponent } from './ts/detail/user-detail.component';

export const routes: Routes = [
  { path: '', redirectTo: 'users', pathMatch: 'full' },
  { path: 'about', component: AboutComponent },
  { path: 'contact', component: ContactComponent },
  { path: 'home', component: HomeComponent },
  { path: 'index', component: HomeComponent },
  { path: 'admins', component: AdminListComponent },
  { path: 'admins/create', component: AdminFormComponent },
  { path: 'admins/:id', component: AdminDetailComponent },
  { path: 'candidatures', component: CandidatureListComponent },
  { path: 'candidatures/create', component: CandidatureFormComponent },
  { path: 'candidatures/:id', component: CandidatureDetailComponent },
  { path: 'entreprises', component: EntrepriseListComponent },
  { path: 'entreprises/create', component: EntrepriseFormComponent },
  { path: 'entreprises/:id', component: EntrepriseDetailComponent },
  { path: 'etudiants', component: EtudiantListComponent },
  { path: 'etudiants/create', component: EtudiantFormComponent },
  { path: 'etudiants/:id', component: EtudiantDetailComponent },
  { path: 'stages', component: StageListComponent },
  { path: 'stages/create', component: StageFormComponent },
  { path: 'stages/:id', component: StageDetailComponent },
  { path: 'users', component: UserListComponent },
  { path: 'users/create', component: UserFormComponent },
  { path: 'users/:id', component: UserDetailComponent },
];